# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9d3924a3ddfb50c6baa839f94c63d4ed"
name = "Pack Pricing"
application_url = "https://shopify.dapperlogic.xyz"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

[auth]
redirect_urls = [
  "https://shopify.dapperlogic.xyz/auth/callback",
  "https://shopify.dapperlogic.xyz/auth/shopify/callback",
  "https://shopify.dapperlogic.xyz/shopify/auth/callback"
]
