# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9d3924a3ddfb50c6baa839f94c63d4ed"
name = "Pack Pricing"
application_url = "https://proportion-removed-post-daughter.trycloudflare.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

[auth]
redirect_urls = [
  "https://proportion-removed-post-daughter.trycloudflare.com/auth/callback",
  "https://proportion-removed-post-daughter.trycloudflare.com/auth/shopify/callback",
  "https://proportion-removed-post-daughter.trycloudflare.com/shopify/auth/callback"
]
